version: '3'
services:
  web:
    build: .
    container_name: proyecto_codigo_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - tu_red_docker

  db:
    image: mysql:8.0
    container_name: tienda_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: tienda_bd
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - tu_red_docker

  selenium:
    image: selenium/video:ffmpeg-4.3.1-20230801
    volumes:
      - ./test-videos:/videos
    depends_on:
      - selenium-chrome
    networks:
      - tu_red_docker

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    environment:
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - tu_red_docker

volumes:
  mysql_data:

networks:
  tu_red_docker:
    external: true