name: PHP Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, xdebug
        coverage: xdebug
        tools: composer:v2

    - name: Get composer cache directory
      id: composer-cache-dir
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      id: composer-cache
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
        composer require --dev emuse/behat-html-formatter

    - name: Run test suite with coverage
      run: |
        mkdir -p public/coverage
        XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-html public/coverage --coverage-text

    - name: Run Behat tests
      run: |
        mkdir -p public/bdd
        vendor/bin/behat --format pretty --format html --out std --out public/bdd

    - name: Create main index.html
      run: |
        echo '<!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Reportes de Pruebas</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 40px;
                    text-align: center;
                    background-color: #f5f5f5;
                }
                .container {
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: white;
                    border-radius: 10px;
                    box-shadow: 0 0 10px rgba(0,0,0,0.1);
                }
                h1 { 
                    color: #333;
                    margin-bottom: 30px;
                }
                .buttons {
                    display: flex;
                    justify-content: center;
                    gap: 20px;
                }
                .button {
                    display: inline-block;
                    padding: 12px 24px;
                    color: white;
                    text-decoration: none;
                    border-radius: 5px;
                    transition: background-color 0.3s;
                }
                .coverage-btn {
                    background-color: #4CAF50;
                }
                .coverage-btn:hover {
                    background-color: #45a049;
                }
                .bdd-btn {
                    background-color: #2196F3;
                }
                .bdd-btn:hover {
                    background-color: #1976D2;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Proyecto SI784-2024-II</h1>
                <div class="buttons">
                    <a href="coverage/index.html" class="button coverage-btn">Ver Reporte de Cobertura</a>
                    <a href="bdd/index.html" class="button bdd-btn">Ver Reporte BDD</a>
                </div>
            </div>
        </body>
        </html>' > public/index.html

    - name: Deploy reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        enable_jekyll: false
        force_orphan: true
        full_commit_message: 'docs: update test reports'