name: Semgrep
on: [push, pull_request]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CalidadU2
        uses: actions/checkout@v3
        with:
          repository: JosueUPT/CalidadU2
          path: CalidadU2

      - name: Setup Git
        run: |
          cd CalidadU2
          git config --global --add safe.directory $(pwd)

      - name: Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          working-directory: ./CalidadU2
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}