name: Semgrep Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semgrep-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Security Scan
        uses: semgrep/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_DEPLOYMENT_ID: "pyfange"
          SEMGREP_REPO_NAME: ${{ github.repository }}
          SEMGREP_BRANCH: ${{ github.ref_name }}
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          config: >- 
            p/default 