name: Sync and Analyze

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-scan:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio actual
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      # Paso 2: Configurar PHP y dependencias
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install dependencies
        run: composer install

      # Paso 3: Ejecutar tests con cobertura
      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      # Paso 4: Sincronizar con el otro repositorio
      - name: Sync repositories
        run: |
          git config --global user.name 'JosueUPT'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/JosueUPT/CalidadU2.git ../CalidadU2
          rsync -av --exclude='.git' --exclude='.github' --exclude='temp_repo' ./ ../CalidadU2/
          cd ../CalidadU2
          git add .
          git commit -m "Sync: Update from source repository" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
          cd ..

      # Paso 5: Análisis de SonarCloud
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=CalidadU2
            -Dsonar.organization=josueupt
            -Dsonar.php.coverage.reportPaths=build/logs/clover.xml