name: Sync Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'JosueUPT'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'

      - name: Clone destination repository
        run: |
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/JosueUPT/CalidadU2.git temp_repo
          cp -r . temp_repo/ 2>/dev/null || :
          cd temp_repo
          git add .
          git commit -m "Sync: Update from source repository"
          git push origin main