name: Sync and Analyze

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: xdebug
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress

      - name: Run test suite with coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Fix code coverage paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' coverage.xml

      - name: Sync repositories
        run: |
          git config --global user.name 'JosueUPT'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git add composer.lock
          git commit -m "Update composer.lock" || echo "No changes to commit"
          git push || echo "No changes to push"
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/JosueUPT/CalidadU2.git ../CalidadU2
          rsync -av --exclude='.git' --exclude='.github' --exclude='temp_repo' ./ ../CalidadU2/
          cd ../CalidadU2
          git add .
          git commit -m "Sync: Update from source repository" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
          cd ..

      - name: Run Semgrep Security Scan
        uses: semgrep/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          args: --sarif --output=semgrep.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          wait-for-processing: true
        if: always()

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
