name: Sync Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Sync repositories
        run: |
          # Configurar git
          git config --global user.name 'JosueUPT'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          
          # Clonar el repositorio destino
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/JosueUPT/CalidadU2.git ../CalidadU2
          
          # Copiar archivos (excluyendo .git)
          rsync -av --exclude='.git' --exclude='temp_repo' ./ ../CalidadU2/
          
          # Commit y push en el repositorio destino
          cd ../CalidadU2
          git add .
          git commit -m "Sync: Update from source repository"
          git push origin main