name: Sync and Analyze

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-scan:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio actual
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      # Paso 2: Configurar PHP y Xdebug
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug
          coverage: xdebug

      # Paso 3: Actualizar composer.lock
      - name: Update Composer dependencies
        run: |
          composer update --no-interaction --no-progress
          composer validate --strict

      # Paso 4: Ejecutar pruebas y generar cobertura
      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      # Paso 5: Verificar cobertura
      - name: Check test coverage
        run: |
          COVERAGE=$(php -r "
            \$xml = new SimpleXMLElement(file_get_contents('coverage.xml'));
            \$metrics = \$xml->xpath('//metrics');
            \$covered = (int)\$metrics[0]['coveredstatements'];
            \$total = (int)\$metrics[0]['statements'];
            echo round((\$covered / \$total) * 100, 2);
          ")
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Test coverage is below 80% ($COVERAGE%)"
            exit 1
          fi
          echo "Test coverage is $COVERAGE%"

      # Paso 6: Sincronizar con el otro repositorio
      - name: Sync repositories
        run: |
          git config --global user.name 'JosueUPT'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git add composer.lock
          git commit -m "Update composer.lock" || echo "No changes to commit"
          git push || echo "No changes to push"
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/JosueUPT/CalidadU2.git ../CalidadU2
          rsync -av --exclude='.git' --exclude='.github' --exclude='temp_repo' ./ ../CalidadU2/
          cd ../CalidadU2
          git add .
          git commit -m "Sync: Update from source repository" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
          cd ..

      # Paso 7: Análisis de SonarCloud
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}