name: Unit Tests Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, xdebug
          coverage: xdebug

      - name: Instalar dependencias
        run: composer install --prefer-dist --no-progress

      - name: Ejecutar pruebas y generar reporte
        run: |
          mkdir -p reports
          XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-html reports/coverage \
                                                --testdox-html reports/testdox.html \
                                                --coverage-text \
                                                tests/Unit/

      - name: Generar resumen
        run: |
          echo "<html><head><title>Resumen de Pruebas</title>
          <style>
            body { font-family: Arial; margin: 40px; }
            .summary { background: #f5f5f5; padding: 20px; border-radius: 5px; }
            .links { margin-top: 20px; }
            .links a { margin-right: 20px; }
          </style></head><body>" > reports/index.html
          
          echo "<h1>Resumen de Pruebas Unitarias</h1>" >> reports/index.html
          echo "<div class='summary'>" >> reports/index.html
          echo "<h2>Cobertura de Código</h2><pre>" >> reports/index.html
          XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text tests/Unit/ >> reports/index.html
          echo "</pre></div>" >> reports/index.html
          
          echo "<div class='links'>
          <h2>Reportes Detallados</h2>
          <a href='coverage/index.html'>Ver Cobertura Detallada</a>
          <a href='testdox.html'>Ver Resultados de Pruebas</a>
          </div>" >> reports/index.html
          
          echo "</body></html>" >> reports/index.html

      - name: Comprimir reportes
        run: |
          cd reports
          zip -r test-report.zip ./*

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/test-report.zip
          retention-days: 30 